import { ReportInput, ReportOutput, UnifiedFinding } from './types.js';

function calculateScore(findings: UnifiedFinding[]): number {
  let score = 100;
  for (const f of findings) {
    switch (f.severity) {
      case 'CRITICAL': score -= 20; break;
      case 'HIGH': score -= 10; break;
      case 'MEDIUM': score -= 5; break;
      case 'LOW': score -= 1; break;
      case 'INFO': score -= 0; break;
    }
  }
  // Extra penalty for many findings
  if (findings.length > 10) score -= Math.min(20, findings.length - 10);
  return Math.max(0, Math.min(100, score));
}

function getVerdict(score: number, hasCritical: boolean): ReportOutput['verdict'] {
  if (hasCritical || score <= 20) return 'CRITICAL';
  if (score <= 40) return 'HIGH';
  if (score <= 60) return 'MODERATE';
  if (score <= 80) return 'GOOD';
  return 'EXCELLENT';
}

function verdictIcon(v: string): string {
  switch (v) {
    case 'CRITICAL': return '🔴 CRITICAL';
    case 'HIGH': return '🟠 HIGH';
    case 'MODERATE': return '🟡 MODERATE';
    case 'GOOD': return '🟢 GOOD';
    case 'EXCELLENT': return '✅ EXCELLENT';
    default: return v;
  }
}

function groupBySeverity(findings: UnifiedFinding[]): Record<string, number> {
  const map: Record<string, number> = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0, INFO: 0 };
  for (const f of findings) {
    map[f.severity] = (map[f.severity] || 0) + 1;
  }
  return map;
}

function owaspComplianceFromFindings(findings: UnifiedFinding[]): Record<string, string> {
  // Simplified mapping based on patternId -> OWASP
  const owaspMap: Record<string, string[]> = {
    'A01 — Broken Access Control': ['CORS', 'IDOR', 'BOLA', 'MASS_ASSIGNMENT'],
    'A02 — Cryptographic Failures': ['JWT', 'CRYPTO', 'PRIVATE_KEY'],
    'A03 — Injection': ['SQLI', 'XSS', 'INJECTION', 'EVAL', 'EXEC', 'NOSQL', 'XXE', 'DESERIAL'],
    'A04 — Insecure Design': ['LOGIC', 'BUSINESS'],
    'A05 — Security Misconfiguration': ['HELMET', 'HEADERS', 'DEBUG', 'CORS'],
    'A06 — Vulnerable Components': ['DEPS', 'SUPPLY'],
    'A07 — Auth Failures': ['AUTH', 'SECRET', 'AWS', 'GITHUB', 'STRIPE', 'JWT'],
    'A08 — Data Integrity': ['DESERIAL', 'SUPPLY'],
    'A09 — Logging & Monitoring': [],
    'A10 — SSRF': ['SSRF'],
  };

  const result: Record<string, string> = {};
  for (const [owasp, keywords] of Object.entries(owaspMap)) {
    const hasFindings = findings.some(f => {
      const pid = f.patternId.toUpperCase();
      return keywords.some(k => pid.includes(k.toUpperCase()));
    });
    if (hasFindings) result[owasp] = '❌ FAIL';
    else result[owasp] = '✅ PASS';
  }
  // If no findings at all, all PASS
  return result;
}

function bar(score: number): string {
  const filled = Math.round(score / 5); // 20 chars max
  const empty = 20 - filled;
  return `[${'█'.repeat(filled)}${'░'.repeat(empty)}] ${score}%`;
}

export function generateReport(input: ReportInput): ReportOutput {
  const { target, findings, type, version, framework } = input;
  const date = input.date || new Date().toISOString().split('T')[0];
  const score = calculateScore(findings);
  const hasCritical = findings.some(f => f.severity === 'CRITICAL');
  const verdict = getVerdict(score, hasCritical);
  const dashboard = groupBySeverity(findings);
  const owasp = owaspComplianceFromFindings(findings);

  // Sort findings by severity then file
  const order = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3, INFO: 4 } as const;
  const sorted = [...findings].sort((a, b) => {
    const oa = order[a.severity as keyof typeof order];
    const ob = order[b.severity as keyof typeof order];
    if (oa !== ob) return oa - ob;
    return a.file.localeCompare(b.file);
  });

  const groupedBySeverity: Record<string, UnifiedFinding[]> = {};
  for (const f of sorted) {
    if (!groupedBySeverity[f.severity]) groupedBySeverity[f.severity] = [];
    groupedBySeverity[f.severity].push(f);
  }

  let md = `# 🛡️ SECURITY AUDIT REPORT — ${type.toUpperCase()}\n`;
  md += `# Generated by CyberAudit v${version} — Deterministic Scanner\n\n`;
  md += `═══════════════════════════════════════════════════════════════\n`;
  md += `              REPORT HEADER\n`;
  md += `═══════════════════════════════════════════════════════════════\n\n`;
  md += `Application     : ${target}\n`;
  md += `Framework(s)    : ${framework || 'auto-detected'}\n`;
  md += `Audit type      : ${type} — deterministic (secrets + web)\n`;
  md += `Audit level     : Standard (deterministic)\n`;
  md += `Date            : ${date}\n`;
  md += `Auditor         : CyberAudit Intelligence v${version} (deterministic scanner)\n`;
  md += `Confidentiality : 🔴 CONFIDENTIAL — Internal use only\n\n`;

  md += `═══════════════════════════════════════════════════════════════\n`;
  md += `              EXECUTIVE SUMMARY\n`;
  md += `═══════════════════════════════════════════════════════════════\n\n`;
  md += `OVERALL VERDICT: ${verdictIcon(verdict)}\n\n`;
  md += `SECURITY SCORE: ${score}/100\n\n`;
  md += `  ${bar(score)}\n\n`;
  md += `  0-20  : 🔴 Critical — Do not deploy\n`;
  md += `  21-40 : 🟠 High — Major fixes required\n`;
  md += `  41-60 : 🟡 Moderate — Significant fixes before prod\n`;
  md += `  61-80 : 🟢 Good — Some fixes recommended\n`;
  md += `  81-100: ✅ Excellent — Ready for production\n\n`;

  md += `VULNERABILITY DASHBOARD\n`;
  md += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
  md += `  🔴 CRITICAL : ${dashboard.CRITICAL || 0} → Block deployment\n`;
  md += `  🟠 HIGH     : ${dashboard.HIGH || 0} → Fix before deployment\n`;
  md += `  🟡 MEDIUM   : ${dashboard.MEDIUM || 0} → Fix within 30 days\n`;
  md += `  🟢 LOW      : ${dashboard.LOW || 0} → Security backlog\n`;
  md += `  ℹ️  INFO     : ${dashboard.INFO || 0} → Recommendations\n\n`;
  md += `  TOTAL : ${findings.length} findings (deterministic)\n\n`;

  if (findings.length > 0) {
    md += `IDENTIFIED BUSINESS RISKS\n`;
    md += `━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
    if (dashboard.CRITICAL > 0) md += `  → Immediate compromise possible via ${sorted.filter(f=>f.severity==='CRITICAL').slice(0,2).map(f=>f.patternId).join(', ')}\n`;
    if (findings.some(f=>f.patternId.includes('SECRET') || f.patternId.includes('AWS'))) md += `  → Credential leak → account takeover, data breach\n`;
    if (findings.some(f=>f.patternId.includes('SQLI') || f.patternId.includes('XSS'))) md += `  → Injection → data exfiltration, user session hijack\n`;
    if (findings.some(f=>f.patternId.includes('JWT'))) md += `  → Auth bypass via JWT flaw\n`;
    md += `\n`;

    md += `IMMEDIATE ACTIONS REQUIRED\n`;
    md += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
    sorted.filter(f=>f.severity==='CRITICAL').slice(0,3).forEach((f,i)=>{
      md += `  ${i+1}. Fix ${f.patternId} in ${f.file}:${f.line} — ${f.severity}\n`;
    });
    if (dashboard.CRITICAL === 0 && dashboard.HIGH > 0) {
      sorted.filter(f=>f.severity==='HIGH').slice(0,3).forEach((f,i)=>{
        md += `  ${i+1}. Fix ${f.patternId} in ${f.file}:${f.line}\n`;
      });
    }
    md += `\n`;
  } else {
    md += `✅ No deterministic findings. Good baseline, proceed to manual audit for business logic.\n\n`;
  }

  md += `═══════════════════════════════════════════════════════════════\n`;
  md += `              DETAILED FINDINGS\n`;
  md += `═══════════════════════════════════════════════════════════════\n\n`;

  if (sorted.length === 0) {
    md += `No findings from deterministic scanners.\n\n`;
  } else {
    let counter = 1;
    for (const sev of ['CRITICAL','HIGH','MEDIUM','LOW','INFO'] as const) {
      const group = groupedBySeverity[sev];
      if (!group || group.length === 0) continue;
      md += `━━ ${sev} (${group.length}) ━━\n\n`;
      for (const f of group) {
        md += `[VULN-${String(counter).padStart(3,'0')}] — ${f.patternId}\n`;
        md += `─────────────────────────────────────────────\n`;
        md += `  Severity      : ${sev === 'CRITICAL' ? '🔴' : sev === 'HIGH' ? '🟠' : sev === 'MEDIUM' ? '🟡' : '🟢'} ${sev}\n`;
        md += `  CVSS Score    : ${f.cvss} (${f.cvssVector})\n`;
        md += `  Scanner       : ${f.scanner}\n`;
        md += `  OWASP         : ${f.owasp || 'N/A'}\n`;
        md += `  CWE           : ${f.cwe || 'N/A'}\n`;
        md += `  File          : ${f.file}\n`;
        md += `  Line          : ${f.line}\n`;
        md += `\n`;
        md += `  ┌─ MATCH ─────────────────────────────────────────────\n`;
        md += `  │ ${f.match.slice(0,200)}\n`;
        md += `  └─────────────────────────────────────────────────────\n\n`;
        md += `  DESCRIPTION\n`;
        md += `  ───────────\n`;
        md += `  ${f.description}\n\n`;
        md += `  REMEDIATION (ready to copy-paste)\n`;
        md += `  ───────────\n`;
        md += `  ${f.remediation}\n\n`;
        md += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n`;
        counter++;
      }
    }
  }

  md += `═══════════════════════════════════════════════════════════════\n`;
  md += `              OWASP TOP 10 2023 COMPLIANCE\n`;
  md += `═══════════════════════════════════════════════════════════════\n\n`;
  for (const [k,v] of Object.entries(owasp)) {
    md += `  ${k.padEnd(35)} : ${v}\n`;
  }
  md += `\n`;

  md += `═══════════════════════════════════════════════════════════════\n`;
  md += `              PRIORITISED REMEDIATION PLAN\n`;
  md += `═══════════════════════════════════════════════════════════════\n\n`;

  const phases: Record<string, UnifiedFinding[]> = {
    'PHASE 1 — IMMEDIATE (Week 1)': groupedBySeverity['CRITICAL'] || [],
    'PHASE 2 — SHORT TERM (Weeks 2-4)': groupedBySeverity['HIGH'] || [],
    'PHASE 3 — MEDIUM TERM (Months 2-3)': groupedBySeverity['MEDIUM'] || [],
    'PHASE 4 — LONG TERM (Backlog)': [...(groupedBySeverity['LOW']||[]), ...(groupedBySeverity['INFO']||[])],
  };

  for (const [phase, items] of Object.entries(phases)) {
    if (items.length === 0) continue;
    md += `${phase}\n`;
    md += `  Objective: ${phase.includes('IMMEDIATE') ? 'Eliminate critical risks' : phase.includes('SHORT') ? 'Eliminate high risks' : phase.includes('MEDIUM') ? 'Address medium risks' : 'Polish'}\n`;
    for (const f of items.slice(0,10)) {
      md += `  □ ${f.patternId} : ${f.file}:${f.line} (${f.severity})\n`;
    }
    if (items.length > 10) md += `  ... and ${items.length - 10} more\n`;
    md += `\n`;
  }

  md += `═══════════════════════════════════════════════════════════════\n`;
  md += `              CONCLUSION\n`;
  md += `═══════════════════════════════════════════════════════════════\n\n`;
  if (verdict === 'CRITICAL') md += `🔴 NO-GO for production. Critical findings must be fixed. Score ${score}/100.\n`;
  else if (verdict === 'HIGH') md += `🟠 NO-GO for production without fixing HIGH findings. Score ${score}/100.\n`;
  else if (verdict === 'MODERATE') md += `🟡 Conditional GO with remediation plan. Score ${score}/100.\n`;
  else if (verdict === 'GOOD') md += `🟢 GO with minor fixes in backlog. Score ${score}/100.\n`;
  else md += `✅ GO for production. Excellent posture. Score ${score}/100.\n`;

  md += `\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
  md += `Report generated by CyberAudit v${version} — Deterministic Scanner\n`;
  md += `Findings are deterministic (regex + patterns), not LLM hallucinations.\n`;
  md += `For full manual audit, run /audit:web, /audit:api, etc. via skill.\n`;
  md += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;

  return {
    markdown: md,
    score,
    verdict,
    dashboard,
    owaspCompliance: owasp,
  };
}
